### ISSUE TITLE
Wrong directory of basic_data folder

### ISSUE THREAD

**Issue by tuanphuc** [skriegman/evosoro#1]
As the title, I found that the basic_data folder is in 
```
evosoro/evosoro/examples/basic_data
```
not in:
```
evosoro/evosoro/basic_data
```
as indicated in the README.md

**Comment by skriegman** [comment]
Good catch, tuanphuc. I jusy updated the readme.

**Comment by suixin777** [comment]
can not run basic.py 
Type "scientific" for more details.
>>> runfile('/home/sx/evosoro/evosoro/examples/basic.py', wdir=r'/home/sx/evosoro/evosoro/examples')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/sx/evosoro/evosoro/examples/basic.py", line 165, in <module>
    my_pop = Population(my_objective_dict, MyGenotype, MyPhenotype, pop_size=POPSIZE)
  File "/home/sx/evosoro/evosoro/examples/../../evosoro/softbot.py", line 389, in __init__
    self.add_random_individual()
  File "/home/sx/evosoro/evosoro/examples/../../evosoro/softbot.py", line 450, in add_random_individual
    ind = SoftBot(self.max_id, self.objective_dict, self.genotype, self.phenotype)
  File "/home/sx/evosoro/evosoro/examples/../../evosoro/softbot.py", line 324, in __init__
    self.genotype = genotype()  # initialize new random genome
  File "/home/sx/evosoro/evosoro/examples/basic.py", line 94, in __init__
    self.add_network(CPPN(output_node_names=["shape", "muscleOrTissue", "muscleType", "tissueType"]))
  File "/home/sx/evosoro/evosoro/examples/../../evosoro/networks.py", line 53, in __init__
    self.mutate()
  File "/home/sx/evosoro/evosoro/examples/../../evosoro/networks.py", line 114, in mutate
    variation_degree = self.add_node()
  File "/home/sx/evosoro/evosoro/examples/../../evosoro/networks.py", line 148, in add_node
    this_edge = random.choice(self.graph.edges())
  File "/usr/lib/python2.7/random.py", line 273, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
  File "/usr/local/lib/python2.7/dist-packages/networkx/classes/reportviews.py", line 926, in __getitem__
    u, v = e
TypeError: 'int' object is not iterable
